name: Superb Digital
favicon: null
layout_spectrum: 0.8090715524740517
typography_spectrum: 0.2467421197798103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8072926057502627
  lightness: 0.5235365200787783
  saturation: 0.6714675242546946
  rhythmicContrast: 0.7896100443322212
purpose: []
